# Generated by Django 3.1.4 on 2020-12-06 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='profile_picture',
            new_name='profile_pic',
        ),
    ]
